# Generated by Django 5.0.2 on 2024-03-01 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_y_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('notas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Desparasitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desparasitante', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FichaDesparasitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('dosis', models.CharField(max_length=100)),
                ('notas', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dueno',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido', 'correo_electronico'), name='unique_cita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.dueno'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.estado'),
        ),
        migrations.AddField(
            model_name='fichadesparasitacion',
            name='desparasitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.desparasitante'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.dueno'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.especie'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.genero'),
        ),
        migrations.AddField(
            model_name='fichadesparasitacion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.raza'),
        ),
        migrations.AddConstraint(
            model_name='fichadesparasitacion',
            constraint=models.UniqueConstraint(fields=('mascota', 'fecha', 'desparasitante'), name='unique_ficha_desparasitante'),
        ),
    ]
